name: Build LaTeX document

on:  
  release:
    types:
      - published

env:
  PDF_NAME: ${{ github.repository }}_${{ github.event.release.tag_name }}_${{ github.sha }}.pdf

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.PDF_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PDF_NAME }}
